sylius_grid:
    templates:
        filter:
            status: '@SetonoSyliusMiintoPlugin/Grid/Filter/status.html.twig'
    grids:
        setono_sylius_miinto_admin_order:
            driver:
                name: doctrine/orm
                options:
                    class: "%setono_sylius_miinto.model.order.class%"
            sorting:
                id: desc
            fields:
                id:
                    type: string
                    label: setono_sylius_miinto.ui.miinto_id
                    sortable: ~
                shop:
                    type: string
                    label: setono_sylius_miinto.ui.shop
                    sortable: ~
                status:
                    type: twig
                    label: setono_sylius_miinto.ui.status
                    options:
                        template: "@SetonoSyliusMiintoPlugin/Admin/Grid/Field/status.html.twig"
                errors:
                    type: twig
                    label: setono_sylius_miinto.ui.errors
                    options:
                        template: "@SetonoSyliusMiintoPlugin/Admin/Grid/Field/errors.html.twig"
                order:
                    type: twig
                    label: setono_sylius_miinto.ui.shop_order
                    options:
                        template: "@SetonoSyliusMiintoPlugin/Admin/Grid/Field/order.html.twig"
            filters:
                id:
                    type: string
                    label: sylius.ui.id
                status:
                    type: status
                    label: sylius.ui.status
