sylius_grid:
    grids:
        setono_sylius_miinto_admin_payment_method_mapping:
            driver:
                name: doctrine/orm
                options:
                    class: "%setono_sylius_miinto.model.payment_method_mapping.class%"
            fields:
                shop:
                    type: twig
                    label: setono_sylius_miinto.ui.shop
                    options:
                        template: "@SetonoSyliusMiintoPlugin/Admin/Grid/Field/shop.html.twig"
                paymentMethod:
                    type: twig
                    label: setono_sylius_miinto.ui.payment_method
                    options:
                        template: "@SetonoSyliusMiintoPlugin/Admin/Grid/Field/data_or_error.html.twig"
                        vars:
                            label: setono_sylius_miinto.ui.payment_method_not_set
            actions:
                item:
                    update:
                        type: update
