sylius_grid:
    grids:
        setono_sylius_miinto_admin_shop:
            driver:
                name: doctrine/orm
                options:
                    class: "%setono_sylius_miinto.model.shop.class%"
            sorting:
                name: asc
            fields:
                id:
                    type: string
                    label: setono_sylius_miinto.ui.miinto_id
                    sortable: ~
                name:
                    type: string
                    label: setono_sylius_miinto.ui.name
                channel:
                    type: twig
                    label: setono_sylius_miinto.ui.channel
                    options:
                        template: "@SetonoSyliusMiintoPlugin/Admin/Grid/Field/data_or_error.html.twig"
                        vars:
                            label: setono_sylius_miinto.ui.channel_not_set
                locale:
                    type: twig
                    label: setono_sylius_miinto.ui.locale
                    options:
                        template: "@SetonoSyliusMiintoPlugin/Admin/Grid/Field/data_or_error.html.twig"
                        vars:
                            label: setono_sylius_miinto.ui.locale_not_set
            actions:
                item:
                    update:
                        type: update
