imports:
    - "@SetonoSyliusMiintoPlugin/Resources/config/grid/setono_sylius_miinto_admin_order.yaml"
    - "@SetonoSyliusMiintoPlugin/Resources/config/grid/setono_sylius_miinto_admin_payment_method_mapping.yaml"
    - "@SetonoSyliusMiintoPlugin/Resources/config/grid/setono_sylius_miinto_admin_shipping_method_mapping.yaml"
    - "@SetonoSyliusMiintoPlugin/Resources/config/grid/setono_sylius_miinto_admin_shipping_type_mapping.yaml"
    - "@SetonoSyliusMiintoPlugin/Resources/config/grid/setono_sylius_miinto_admin_shop.yaml"

framework:
    messenger:
        buses:
            setono_sylius_miinto.command_bus: ~
            
    workflows:
        setono_sylius_miinto_order_processing:
            type: 'state_machine'
            marking_store:
                type: 'method'
                property: 'status'
            supports:
                - "%setono_sylius_miinto.model.order.class%"
            initial_marking: pending
            places:
                - pending
                - processing
                - processed
                - errored
            transitions:
                to_pending:
                    from: errored
                    to: pending
                start_processing:
                    from: [pending]
                    to:   processing
                process:
                    from: processing
                    to:   processed
                errored:
                    from: [pending, processing]
                    to:   errored

