imports:
    - "@SetonoSyliusMiintoPlugin/Resources/config/grid/setono_sylius_miinto_admin_order.yaml"
    - "@SetonoSyliusMiintoPlugin/Resources/config/grid/setono_sylius_miinto_admin_payment_method_mapping.yaml"
    - "@SetonoSyliusMiintoPlugin/Resources/config/grid/setono_sylius_miinto_admin_shipping_method_mapping.yaml"
    - "@SetonoSyliusMiintoPlugin/Resources/config/grid/setono_sylius_miinto_admin_shipping_type_mapping.yaml"
    - "@SetonoSyliusMiintoPlugin/Resources/config/grid/setono_sylius_miinto_admin_shop.yaml"
    - "@SetonoSyliusMiintoPlugin/Resources/config/workflow.yaml"
